// File generated by FlutterFire CLI / KalaSetu Firebase Config
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLIMe_Mz7nY7xJ-bWblDqXoGQlyz-__UI',
    appId: '1:715970678839:web:911bc5b3024b5e46496fb2',
    messagingSenderId: '715970678839',
    projectId: 'kalasetu-53f92',
    authDomain: 'kalasetu-53f92.firebaseapp.com',
    storageBucket: 'kalasetu-53f92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLIMe_Mz7nY7xJ-bWblDqXoGQlyz-__UI',
    appId: '1:715970678839:android:911bc5b3024b5e46496fb2',
    messagingSenderId: '715970678839',
    projectId: 'kalasetu-53f92',
    storageBucket: 'kalasetu-53f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLIMe_Mz7nY7xJ-bWblDqXoGQlyz-__UI',
    appId: '1:715970678839:ios:911bc5b3024b5e46496fb2',
    messagingSenderId: '715970678839',
    projectId: 'kalasetu-53f92',
    storageBucket: 'kalasetu-53f92.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );
}
